[build-system]
requires = ["setuptools>=75.3.0"]
build-backend = "setuptools.build_meta"

[project]
name = "TA.support"
version = "1.4.2"
description = "Biblioteca de suporte do Transfero Academy"
authors = [{name = "Seu Nome", email = "sergio.wellington@email.com"}]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "fastapi",
    "pyjwt",
    "python-dotenv",
    "sqlalchemy[asyncio]>=2.0",
    "google-auth",
    "python-dateutil"
]
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"TA.support" = ["locales/*.json"]  # ← inclui o json no pacote